project:
  type: website
  output-dir: docs
  # On exclut les fichiers .tex et le dossier tikz du processus de compilation
  # pour éviter que GitHub ne cherche une installation LaTeX (TinyTeX)
  render:
    - "*.qmd"
    - "!*.tex"
    - "!code_tikz/*"
  
  # On définit ces fichiers comme ressources pour qu'ils soient quand même 
  # copiés dans le dossier final et accessibles par lien hypertexte
  resources:
    - "*.tex"
    - "code_tikz/*.tex"
    
abstract: |
  Ce document constitue un socle théorique et pédagogique conçu pour accompagner des formations appliquées à la convergence entre physique quantique et réseaux. 
  À travers une approche privilégiant le formalisme matriciel de Heisenberg (1925) et les séries de Fourier, il explore la dualité onde-corpuscule de De Broglie, le principe d'incertitude et l'équation de Schrödinger. 
  L'étude propose également une réflexion originale sur les analogies entre les formalismes quantiques et les architectures décentralisées (Blockchain), offrant aux ingénieurs un cadre conceptuel pour appréhender la seconde révolution quantique.

metadata:
  keywords: 
    - "Mécanique Quantique"
    - "Heisenberg 1925"
    - "Formalisme matriciel"
    - "Louis de Broglie"
    - "Séries de Fourier"
    - "Équation de Schrödinger"
    - "Intrication quantique"
    - "Blockchain et Quantique"
    - "Informatique Quantique"
    - "Algèbre Linéaire Physique"
    - "Innovation technologique"
    - "Caporali Conseil"

website:
  title: "Blog Scientifique : le laboratoire de Caporali Conseil"
  
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Accueil
      - href: cours/plan.qmd
        text: "Programme de Cours"
      - text: "Publications"
        menu:
          - text: "Articles de Recherche"
            href: publications/articles.qmd
          - text: "Présentations et Conférences"
            href: publications/presentations.qmd
          - text: "Fondement théorique de la quantique (CC-BY)"
            href: publications/fondements.qmd
    right:
      - icon: github
        href: https://github.com/Caporali-Conseil
  
  page-footer:
    right: "Caporali Conseil | Tous droits réservés | 2026"
    left: "Basé sur les Sciences Physiques et le MAOS"

format:
  html:
    theme: united
    css: custom_styles.css
    toc: true
    # Support mathématique pour la physique quantique sans avoir besoin de LaTeX
    html-math-method: katex
    code-copy: true