project:
  type: website
  title: "Blog Scientifique : le laboratoire de Caporali Conseil"
  output-dir: docs

website:
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - href: cours/plan.qmd
        text: "Programme de Cours"
      - text: "Publications"
        menu:
          - text: "Articles de Recherche"
            href: publications/articles.qmd
          - text: "Présentations et Conférences"
            href: publications/presentations.qmd
          - text: "Fondement theorique de la quantique (CC-BY)"
            href: publications/fondements.qmd
    right:
      - href: contact.qmd
        text: Contacter
      - icon: github
        href: "https://github.com/votre-compte"
      - icon: linkedin
        href: "https://linkedin.com/in/votre-profil"

  page-footer:
    right: "Caporali Conseil | Tous droits réservés | 2026"
    left: "Basé sur les Sciences Physiques et le MAOS"

format:
  html:
    theme: united
    css: custom_styles.css
    toc: true